import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { parseTrecRag2026TopicsTsv } from "../retrieval/topics";
import { generateQuery2Doc } from "../retrieval/query2doc";
import { createLlmClient, generateJsonWithRetry } from "../../llm/create";
import { normalizeLlmClientConfig, safeLlmConfigForArtifacts, type RawLlmClientConfig } from "../../llm/config";
import type { LlmAttemptTrace, LlmClient, LlmJsonValidationResult } from "../../llm/types";
import { buildAnswerGenerationPrompt, buildCompactAnswerGenerationPrompt, buildComprehensiveAnswerPrompt, buildAspectDecompositionPrompt, buildAspectAnswerPrompt, buildReflectionPrompt, buildGroundedRevisionPrompt } from "../agentic-rag-baseline/prompts";
import { verifyCitations } from "./citation_verify";
import { denseScores } from "../retrieval/dense_rerank";
import { reattributeCitations } from "./citation_reattribute";
import { AGENTIC_RAG_BASELINE_PROMPT_VERSION, type AgenticRagBaselineConfig, type AgenticRagOutputObject, type TopicIdentity } from "../agentic-rag-baseline/contracts";
import { normalizeRagOutputObjectReferences, validateRagOutputObjectStrict } from "../agentic-rag-baseline/validation";
import { buildExtractiveFallbackAnswerDraft, type AgenticRagBaselineReadDoc } from "../agentic-rag-baseline/fallback";
import { AgenticRagValidationError } from "../agentic-rag-baseline/validation";
import { evaluateRankings, type Qrels, type Rankings } from "../../evaluation/retrieval_metrics";
import { rerankWithCrossEncoder, type RerankCandidate } from "../retrieval/cross_encoder_rerank";

type Topic={qid:string;title:string;narrative:string}; type Hit={docid:string;score:number}; type ReadDoc=AgenticRagBaselineReadDoc; type AnswerDraft={references:string[];answer:Array<{text:string;citations:number[]}>}; type Judge={enough:boolean;missing_aspects:string[];followup_queries:string[]};
export type IterativeOptions={runId:string;teamId:string;outputDir:string;topicsPath:string;qrelsDir:string;pyseriniBaseUrl:string;pyseriniIndex:string;pyseriniTokenEnv:string;limitTopics?:number;initialDocs:number;docsPerIteration:number;maxDocumentsRead:number;maxIterations:number;documentReadLimit:number;llm:RawLlmClientConfig;force?:boolean;resume?:boolean;env?:NodeJS.ProcessEnv};
const POLICY={retrieval_policy:"iterative-agentic-anchor-bm25-weighted-rrf-w025-query2doc-fusion-peraspect-official-top5000-varK",output_depth:5000,bm25_anchor_weight:1,followup_query_weight:0.25,rrf_k:60,rerank_depth:100,q2d_enabled:true,q2d_weight:1.0,q2d_query_repeat:5,fusion_dense:true,fusion_bm25_weight:1.0,fusion_ce_weight:1.0,fusion_dense_weight:1.0,fusion_rrf_k:60,comprehensive_answer:true,citation_verify:true,support_threshold:0.4,answer_doc_chars:1600,answer_max_tokens:4096,per_aspect_generation:true,aspect_docs:4,aspect_search_depth:100,aspect_max_tokens:1500,aspect_rounds:3,aspect_target_sentences:5,reflection:true,reflection_max_gaps:2,reattribute:true,reattribute_threshold:0.3,reattribute_max_cites:2,vark_threshold:0.5,vark_min:4,vark_max:15,llm_revise:true,revise_snippet_chars:1200,revise_max_tokens:3000} as const; const CUTS=[10,20,50,100,500,1000],NDCG=[10,20,100,1000];
// Variable-k submission (Piika-aligned): per topic keep only the confident docs (ce_calibrated >= tau),
// clamped to [min,max], instead of padding to a fixed cutoff. Reads the persisted fusion_scores.json.
function writeVariableKSubmission(out:string,topics:{qid:string}[],runId:string,tau:number,minK:number,maxK:number){
  const lines:string[]=[]; const counts:Record<string,number>={};
  for(const t of topics){ const p=join(out,"topics",`${t.qid}.fusion_scores.json`); if(!existsSync(p))continue; const fsj=readIf(p) as any[]; if(!Array.isArray(fsj)||fsj.length===0)continue;
    const confident=fsj.filter(x=>typeof x.ce_calibrated==="number"&&x.ce_calibrated>=tau).length;
    let k=confident; if(k<minK)k=minK; if(k>maxK)k=maxK; if(k>fsj.length)k=fsj.length; counts[t.qid]=k;
    fsj.slice(0,k).forEach((x,i)=>lines.push(`${t.qid} Q0 ${x.docid} ${i+1} ${(Number(x.fused)||0).toFixed(8)} ${runId}`)); }
  writeFileSync(join(out,"submission_variable_k.trec"),lines.join("\n")+(lines.length?"\n":""));
  writeJson(join(out,"variable_k_counts.json"),counts);
}
async function rerankTopOfRanking(o:IterativeOptions,topic:Topic,ranking:{docid:string;rank:number;score:number}[],readDocs:Map<string,ReadDoc>,env:NodeJS.ProcessEnv,depth:number,out:string){
  const head=ranking.slice(0,depth), tail=ranking.slice(depth);
  const candidates:RerankCandidate[]=[]; const unfetched:{docid:string;score:number}[]=[];
  for(const entry of head){
    const cached=readDocs.get(entry.docid);
    if(cached){candidates.push({docid:entry.docid,text:cached.text});continue;}
    try{const d=await readDoc(o,entry.docid,o.documentReadLimit,env); if(d.found)candidates.push({docid:entry.docid,text:d.text}); else unfetched.push(entry); await sleep(150);}
    catch{unfetched.push(entry);}
  }
  if(candidates.length===0){writeJson(join(out,"topics",`${topic.qid}.fusion_scores.json`),[]);return ranking;}
  // BM25 rank = order candidates were taken from the fused ranking.
  const bm25Rank=new Map<string,number>(); candidates.forEach((c,i)=>bm25Rank.set(c.docid,i));
  // CrossEncoder signal.
  const reranked=await rerankWithCrossEncoder(topic.narrative,candidates);
  const ceRank=new Map<string,number>(); reranked.forEach((r,i)=>ceRank.set(r.docid,i));
  const ceCal=new Map<string,number>(); reranked.forEach(r=>ceCal.set(r.docid,r.calibratedScore));
  // Dense signal (optional, best-effort — if the embeddings API fails, fall back to BM25+CE only).
  let denseRank=new Map<string,number>(); let denseCos=new Map<string,number>();
  if(POLICY.fusion_dense){ try{ denseCos=await denseScores(topic.narrative,candidates,env); const sorted=[...candidates].map(c=>c.docid).sort((a,b)=>(denseCos.get(b)??0)-(denseCos.get(a)??0)); sorted.forEach((d,i)=>denseRank.set(d,i)); }catch{ denseRank=new Map(); } }
  const K=POLICY.fusion_rrf_k, useDense=denseRank.size>0;
  const fused=candidates.map(c=>{ const rb=bm25Rank.get(c.docid)??candidates.length, rc=ceRank.get(c.docid)??candidates.length, rd=denseRank.get(c.docid)??candidates.length;
    let s=POLICY.fusion_bm25_weight/(K+rb+1)+POLICY.fusion_ce_weight/(K+rc+1); if(useDense)s+=POLICY.fusion_dense_weight/(K+rd+1);
    return {docid:c.docid,fused:s}; }).sort((a,b)=>b.fused-a.fused);
  writeJson(join(out,"topics",`${topic.qid}.fusion_scores.json`),fused.map(f=>({docid:f.docid,fused:f.fused,bm25_rank:bm25Rank.get(f.docid),ce_rank:ceRank.get(f.docid),dense_rank:useDense?denseRank.get(f.docid):null,ce_calibrated:ceCal.get(f.docid)??null,dense_cosine:useDense?(denseCos.get(f.docid)??null):null})));
  const newHead=[...fused.map(f=>({docid:f.docid,score:f.fused})),...unfetched];
  return[...newHead,...tail].map((e,i)=>({docid:e.docid,rank:i+1,score:e.score}));
}
export async function runIterativeAgenticRag(o:IterativeOptions){const env=o.env??process.env,out=resolve(o.outputDir); if(o.force)rmSync(out,{recursive:true,force:true}); mkdirSync(join(out,"topics"),{recursive:true}); const llmCfg=normalizeLlmClientConfig(o.llm),llm=createLlmClient(llmCfg,env); const cfg:AgenticRagBaselineConfig={runId:o.runId,teamId:o.teamId,mode:"dev",promptVersion:AGENTIC_RAG_BASELINE_PROMPT_VERSION}; const topics=parseTrecRag2026TopicsTsv(readFileSync(resolve(o.topicsPath),"utf8")).map(t=>({qid:t.topicId,title:"",narrative:t.narrative})).slice(0,o.limitTopics??Infinity);
writeJson(join(out,"config.json"),{run_id:o.runId,team_id:o.teamId,policy:POLICY,initial_docs:o.initialDocs,docs_per_iteration:o.docsPerIteration,max_documents_read:o.maxDocumentsRead,max_iterations:o.maxIterations,document_read_limit:o.documentReadLimit,llm:safeLlmConfigForArtifacts(llmCfg)});
const summary={run_id:o.runId,selected_topics:topics.length,processed_count:0,failed_count:0,iterations_by_topic:{} as Record<string,number>,stop_reason_by_topic:{} as Record<string,string>,llm_call_count:0,llm_failed_call_count:0,llm_retry_count:0,judge_fallback_count:0,average_documents_read_successful:0};
for(const [idx,t] of topics.entries()){const sp=join(out,"topics",`${t.qid}.status.json`); if(o.resume&&existsSync(sp)&&readIf(sp)?.status==="completed"){console.error(`skip ${t.qid}`);continue;} try{const r=await processTopic({topic:t,o,llm,cfg,out,env,summary}); writeJson(join(out,"topics",`${t.qid}.iteration_trace.json`),r.iterationTrace); writeJson(join(out,"topics",`${t.qid}.judge_trace.json`),r.judgeTrace); writeJson(join(out,"topics",`${t.qid}.retrieval-trace.json`),r.retrievalTrace); writeJson(join(out,"topics",`${t.qid}.rag-draft.json`),r.ragObject); writeJson(join(out,"topics",`${t.qid}.validation.json`),r.validation); writeFileSync(join(out,"topics",`${t.qid}.runfile.trec`),topicRun(t.qid,r.ranking,o.runId)); writeJson(join(out,"topics",`${t.qid}.final_read_docs_trace.json`),r.readTrace); writeJson(sp,{topic_id:t.qid,status:"completed",stop_reason:r.stopReason,iterations:r.iterations}); summary.processed_count++; summary.iterations_by_topic[t.qid]=r.iterations; summary.stop_reason_by_topic[t.qid]=r.stopReason; console.error(`${idx+1}/${topics.length} ${t.qid} iter=${r.iterations} stop=${r.stopReason} read=${r.readTrace.documents_read_successful}`);}catch(e){summary.failed_count++; const issues=e instanceof AgenticRagValidationError?e.issues:undefined; writeJson(sp,{topic_id:t.qid,status:"failed",error:redact(e instanceof Error?e.message:String(e),env),...(issues?{issues}:{})}); console.error(`${idx+1}/${topics.length} ${t.qid} FAILED${issues?" "+issues.map(i=>i.code).join(","):""}`);} await sleep(500);}
const rankings=assemble(out,topics), runfile=render(rankings,topics.map(t=>t.qid),o.runId); writeFileSync(join(out,"candidate_pool_top5000.trec"),runfile); writeFileSync(join(out,"retrieval.internal.trec-run.tsv"),runfile); writeVariableKSubmission(out,topics,o.runId,POLICY.vark_threshold,POLICY.vark_min,POLICY.vark_max); const completed=topics.filter(t=>readIf(join(out,"topics",`${t.qid}.status.json`))?.status==="completed"); const rags=completed.map(t=>readIf(join(out,"topics",`${t.qid}.rag-draft.json`))); writeFileSync(join(out,"rag_output_trec_rag_2026.jsonl"),rags.map(x=>JSON.stringify(x)).join("\n")+(rags.length?"\n":"")); writeJsonl(join(out,"iteration_trace.jsonl"),completed.map(t=>readIf(join(out,"topics",`${t.qid}.iteration_trace.json`))).flat()); const readTraces=completed.map(t=>readIf(join(out,"topics",`${t.qid}.final_read_docs_trace.json`))); writeJsonl(join(out,"final_read_docs_trace.jsonl"),readTraces); writeJsonl(join(out,"retrieval_trace.jsonl"),completed.map(t=>readIf(join(out,"topics",`${t.qid}.retrieval-trace.json`)))); const failed=topics.map(t=>readIf(join(out,"topics",`${t.qid}.status.json`))).filter((s:any)=>s?.status==="failed").map((s:any)=>({topic_id:s.topic_id,error:s.error})); writeJson(join(out,"failed_topics.json"),failed); const metrics=evalAll(qrelsPaths(resolve(o.qrelsDir)),topics.map(t=>t.qid),rankings); writeJson(join(out,"metrics.json"),metrics.summary); writeJson(join(out,"per_topic_metrics.json"),metrics.perTopic); const validation={ok:failed.length===0&&rags.length===topics.length,output_count:rags.length,expected_count:topics.length}; writeJson(join(out,"validation.json"),validation); summary.failed_count=failed.length; summary.average_documents_read_successful=readTraces.reduce((s:any,x:any)=>s+(x?.documents_read_successful??0),0)/(readTraces.length||1); writeJson(join(out,"run-summary.internal.json"),summary); writeFileSync(join(out,"provenance.md"),`# Iterative agentic RAG\n\nNo RAGDoll. No qrels query selection. No source_run_dir.\n`); return{outputDir:out,validation};}
async function processTopic(a:{topic:Topic;o:IterativeOptions;llm:LlmClient;cfg:AgenticRagBaselineConfig;out:string;env:NodeJS.ProcessEnv;summary:any}){const queries=[a.topic.narrative], runs:Hit[][]=[], weights:number[]=[]; const anchor=await search(a.o,a.topic.narrative,5000,a.env); runs.push(anchor); weights.push(POLICY.bm25_anchor_weight); const readDocs=new Map<string,ReadDoc>(), failedRead:string[]=[]; const iterationTrace:any[]=[], judgeTrace:any[]=[];
// Query2Doc: one LLM call generates a pseudo-answer passage; its BM25 run is fused (weighted RRF) with the protected raw-narrative anchor. Additive recall signal, everything downstream unchanged.
if(POLICY.q2d_enabled){const q2d=await generateQuery2Doc(a.llm,a.topic.narrative,{queryRepeat:POLICY.q2d_query_repeat,maxPseudoDocWords:180,maxTokens:400}); writeJson(join(a.out,"topics",`${a.topic.qid}.query2doc.json`),{topic_id:a.topic.qid,ok:q2d.ok,query_repeat:POLICY.q2d_query_repeat,q2d_weight:POLICY.q2d_weight,pseudo_doc:q2d.pseudoDoc,expanded_query:q2d.expandedQuery}); if(q2d.ok){const q2dRun=await search(a.o,q2d.expandedQuery,5000,a.env); runs.push(q2dRun); weights.push(POLICY.q2d_weight); queries.push(`[query2doc] ${q2d.expandedQuery.slice(0,200)}`); await sleep(250);}}
let ranking=weightedRrf(runs,weights,POLICY.output_depth,POLICY.rrf_k), stopReason="max_iterations", iterations=0; await readNew({o:a.o,hits:ranking,readDocs,failedRead,count:a.o.initialDocs,query:a.topic.narrative,env:a.env});
const writePartial=()=>writeTopicPartial({out:a.out,topic:a.topic,iterationTrace,judgeTrace,queries,runs,ranking,readDocs,failedRead});
for(let it=0;it<a.o.maxIterations;it++){iterations=it+1; let judge:Judge; try{judge=await judgeEvidence({topic:a.topic,llm:a.llm,readDocs,queries,out:a.out,env:a.env,summary:a.summary,iteration:it}); judgeTrace.push({iteration:it,judge});}catch(e){a.summary.judge_fallback_count++; const err=redact(e instanceof Error?e.message:String(e),a.env); const code=classifyJudgeStopReason(err); stopReason=code; judgeTrace.push({iteration:it,error_code:code,error:err}); iterationTrace.push({topic_id:a.topic.qid,iteration:it,queries:[...queries],documents_read_successful:readDocs.size,judge_error:{error_code:code,message:err},stop_reason:stopReason,ranking_top10:ranking.slice(0,10)}); writePartial(); break;} let iterationStopReason="continue"; if(judge.enough){stopReason="enough"; iterationStopReason=stopReason; iterationTrace.push({topic_id:a.topic.qid,iteration:it,queries:[...queries],documents_read_successful:readDocs.size,judge,stop_reason:iterationStopReason,ranking_top10:ranking.slice(0,10)}); writePartial(); break;} if(readDocs.size>=a.o.maxDocumentsRead){stopReason="max_documents_read"; iterationStopReason=stopReason; iterationTrace.push({topic_id:a.topic.qid,iteration:it,queries:[...queries],documents_read_successful:readDocs.size,judge,stop_reason:iterationStopReason,ranking_top10:ranking.slice(0,10)}); writePartial(); break;} if(it===a.o.maxIterations-1){stopReason="max_iterations"; iterationStopReason=stopReason; iterationTrace.push({topic_id:a.topic.qid,iteration:it,queries:[...queries],documents_read_successful:readDocs.size,judge,stop_reason:iterationStopReason,ranking_top10:ranking.slice(0,10)}); writePartial(); break;} const fqs=validateFollowups(judge.followup_queries,queries,a.topic.narrative); if(fqs.length===0){stopReason="no_valid_followup_query"; iterationStopReason=stopReason; iterationTrace.push({topic_id:a.topic.qid,iteration:it,queries:[...queries],documents_read_successful:readDocs.size,judge,stop_reason:iterationStopReason,ranking_top10:ranking.slice(0,10)}); writePartial(); break;} iterationTrace.push({topic_id:a.topic.qid,iteration:it,queries:[...queries],documents_read_successful:readDocs.size,judge,followup_queries:fqs,stop_reason:iterationStopReason,ranking_top10:ranking.slice(0,10)}); for(const q of fqs){queries.push(q); const h=await search(a.o,q,5000,a.env); runs.push(h); weights.push(POLICY.followup_query_weight); await sleep(250);} ranking=weightedRrf(runs,weights,POLICY.output_depth,POLICY.rrf_k); await readNew({o:a.o,hits:ranking,readDocs,failedRead,count:a.o.docsPerIteration,query:"weighted_rrf_fused",env:a.env}); writePartial(); if(readDocs.size>=a.o.maxDocumentsRead&&it+1>=a.o.maxIterations)stopReason="max_iterations";}
if(stopReason==="max_iterations"&&readDocs.size>=a.o.maxDocumentsRead)stopReason="max_documents_read"; ranking=await rerankTopOfRanking(a.o,a.topic,ranking,readDocs,a.env,POLICY.rerank_depth,a.out); const ragObject=await answer({topic:a.topic,o:a.o,cfg:a.cfg,llm:a.llm,readDocs,out:a.out,env:a.env,summary:a.summary}); const validation=validateRagOutputObjectStrict(ragObject,{config:a.cfg,topic:a.topic,readDocids:new Set(readDocs.keys())}); if(!validation.ok)throw new Error(`RAG validation failed: ${validation.issues.map(i=>i.code).join(",")}`); const cited=[...new Set(ragObject.answer.flatMap(s=>s.citations).map(i=>ragObject.references[i]).filter(Boolean))]; return{ranking,ragObject,validation,iterationTrace,judgeTrace,iterations,stopReason,readTrace:{topic_id:a.topic.qid,candidate_pool_size:ranking.length,documents_read_attempted:readDocs.size+failedRead.length,documents_read_successful:readDocs.size,read_docids:[...readDocs.keys()],failed_read_docids:failedRead,final_answer_cited_docids:cited},retrievalTrace:buildRetrievalTrace(a.topic,queries,runs,ranking)};}
async function judgeEvidence(a:{topic:TopicIdentity;llm:LlmClient;readDocs:Map<string,ReadDoc>;queries:string[];out:string;env:NodeJS.ProcessEnv;summary:any;iteration:number}){const prompt=["Return ONLY one JSON object. No markdown. No explanation.",'Required schema: {"enough":boolean,"queries":string[]}',"If the evidence already supports the topic, return {\"enough\":true,\"queries\":[]}.","If evidence is insufficient, return {\"enough\":false,\"queries\":[...]} with 1-3 BM25 keyword queries.","Query rules: 4-12 English tokens; keyword phrase, not sentence/question; one aspect only; no duplicates.","Forbidden words: obtain, find, source, sources, detail, detailed, comprehensive, concrete, examples, overview, history, impact, provide, explain.",`Previous queries: ${JSON.stringify(a.queries)}`,`Topic: ${a.topic.narrative}`,"Evidence:",[...a.readDocs.values()].map((d,i)=>`[${i}] ${d.docid}\n${d.text.slice(0,1200)}`).join("\n\n")].join("\n"); let lastError="LLM_JSON_PARSE_FAILED"; for(let attempt=1;attempt<=5;attempt++){const started=Date.now(); try{const result=await a.llm.generate({messages:[{role:"user",content:prompt}],temperature:0,maxTokens:2000,responseFormat:"json_object"}); const parsed=parseJudgeResponse(result.text,a.queries,a.topic.narrative); recordAttempt({attempt:{attempt,provider:result.provider,model:result.model,latencyMs:result.latencyMs,success:parsed.ok,outputChars:result.text.length,...(parsed.ok?{}:{errorCode:"LLM_JSON_PARSE_FAILED"}),...(result.requestId?{requestId:result.requestId}:{}),...(result.usage?{usage:result.usage}:{})},stage:"judge",qid:a.topic.qid,out:a.out,env:a.env,summary:a.summary}); if(parsed.ok)return parsed.value; lastError=parsed.message; }catch(e){lastError=redact(e instanceof Error?e.message:String(e),a.env); recordAttempt({attempt:{attempt,provider:a.llm.provider,model:a.llm.model,latencyMs:Date.now()-started,success:false,errorCode:/empty assistant message/i.test(lastError)?"LLM_EMPTY_ASSISTANT_MESSAGE":/429/.test(lastError)?"LLM_RATE_LIMIT":/5\\d\\d/.test(lastError)?"LLM_SERVER_ERROR":"LLM_PROVIDER_FAILED",outputChars:0},stage:"judge",qid:a.topic.qid,out:a.out,env:a.env,summary:a.summary});} if(attempt<5)await sleep(300*2**attempt);} throw new Error(lastError||"LLM_JSON_PARSE_FAILED");}
function validateJudge(v:unknown,prev:string[],anchor:string):LlmJsonValidationResult<Judge>{if(!isRecord(v)||typeof v.enough!=="boolean")return{ok:false,message:"judge shape"}; const rawQueries=Array.isArray((v as any).queries)?(v as any).queries:Array.isArray((v as any).followup_queries)?(v as any).followup_queries:[]; const missing=Array.isArray((v as any).missing_aspects)?(v as any).missing_aspects.map(String):[]; const legal=validateFollowups(rawQueries,prev,anchor); return{ok:true,value:{enough:Boolean((v as any).enough),missing_aspects:missing,followup_queries:(v as any).enough?[]:legal}};}
function parseJudgeResponse(text:string,prev:string[],anchor:string):LlmJsonValidationResult<Judge>{const json=extractObjectCandidate(text); if(json){try{const parsed=JSON.parse(json); return validateJudge(parsed,prev,anchor);}catch{}} const lines=text.split(/\r?\n|,/).map(x=>x.replace(/^[-*\d.\s\"']+/,"").replace(/[\"']+$/,"").trim()).filter(Boolean); const legal=validateFollowups(lines,prev,anchor); if(legal.length>0)return{ok:true,value:{enough:false,missing_aspects:[],followup_queries:legal}}; if(/\benough\b\s*[:=]\s*true|\bsufficient\b/i.test(text))return{ok:true,value:{enough:true,missing_aspects:[],followup_queries:[]}}; return{ok:false,message:"LLM_JSON_PARSE_FAILED"};}
function extractObjectCandidate(text:string){const fenced=/```(?:json)?\s*([\s\S]*?)```/i.exec(text); const t=(fenced?fenced[1]:text).trim(); if(t.startsWith("{")&&t.endsWith("}"))return t; const a=t.indexOf("{"), b=t.lastIndexOf("}"); return a>=0&&b>a?t.slice(a,b+1):null;}
const BAD=new Set("obtain find source sources detail detailed comprehensive concrete examples evidence information overview history impact provide directly addresses address account explain and".split(" ")); function toks(q:string){return q.toLowerCase().match(/[a-z0-9-]+/g)??[]} function validateFollowups(qs:unknown[],prev:string[],anchor:string){const prevNorm=new Set(prev.map(q=>toks(q).join(" "))); const anchorSet=new Set(toks(anchor)); const out:string[]=[]; for(const raw of qs.map(String)){const q=raw.trim().replace(/\s+/g," "); const t=toks(q), norm=t.join(" "); if(t.length<4||t.length>12||/[?{}.;:]|```/.test(q)||t.some(x=>BAD.has(x))||prevNorm.has(norm)||out.some(x=>toks(x).join(" ")===norm))continue; const overlap=t.filter(x=>anchorSet.has(x)).length/Math.max(1,new Set([...t,...anchorSet]).size); if(overlap>0.75)continue; out.push(q); if(out.length>=3)break;} return out;}
// v4-port per-aspect answer: for each aspect run its OWN BM25 search + reads, generate a few grounded
// sentences from that aspect's targeted evidence, then merge all aspects into one cited answer. This is
// the mechanism (targeted per-aspect evidence) that lets v4 reach high nugget coverage. It only feeds
// generation — the R-task ranking is unchanged (approach ①).
// LLMs often echo their local citation index inline (e.g. "... revenue [2]."). After merging per-aspect
// sub-answers those inline markers are stale (the structured `citations` field is remapped, the text is not),
// so strip them — the citations array is the single source of truth.
function stripInlineCitations(text:string):string{return text.replace(/\s*\[\d+(?:\s*,\s*\d+)*\]/g,"").replace(/\s+([.,;:])/g,"$1").replace(/\s{2,}/g," ").trim();}
// Answer ONE aspect with up to POLICY.aspect_rounds rounds: each round reads a deeper batch of that
// aspect's ranking and writes NEW sentences (told not to repeat prior ones), accumulating evidence —
// this is v4's "dig deeper per sub-question" behaviour. Mutates docidText/shared with docs it reads.
async function answerOneAspect(a:{topic:TopicIdentity;o:IterativeOptions;llm:LlmClient;out:string;env:NodeJS.ProcessEnv;summary:any},aspect:string,docidText:Map<string,string>,shared:Map<string,ReadDoc>):Promise<{sentences:{text:string;docids:string[]}[];docsUsed:number}>{
  let hits:Hit[]=[]; try{hits=await search(a.o,aspect,POLICY.aspect_search_depth,a.env);}catch{hits=[];}
  const out:{text:string;docids:string[]}[]=[]; let cursor=0, docsUsed=0;
  for(let round=0;round<POLICY.aspect_rounds;round++){
    const docs:{docid:string;text:string}[]=[];
    while(docs.length<POLICY.aspect_docs&&cursor<hits.length){ const h=hits[cursor++]; let text:string|undefined=docidText.get(h.docid);
      if(text===undefined){ try{const d=await readDoc(a.o,h.docid,a.o.documentReadLimit,a.env); await sleep(200); if(!d.found)continue; const ft=d.text; text=ft; docidText.set(h.docid,ft); if(!shared.has(h.docid))shared.set(h.docid,{docid:h.docid,text:ft,truncated:d.truncated,rankHint:0,query:`per_aspect:${aspect.slice(0,40)}`});}catch{continue;}}
      if(text===undefined)continue;
      docs.push({docid:h.docid,text:text.slice(0,POLICY.answer_doc_chars)}); }
    if(docs.length===0)break;
    docsUsed+=docs.length;
    try{ const draft=await generateJsonWithRetry({client:a.llm,messages:[{role:"user",content:buildAspectAnswerPrompt({topic:a.topic,aspect,documents:docs,alreadyWritten:out.map(s=>s.text)})}],temperature:0,maxTokens:POLICY.aspect_max_tokens,validate:validateAnswer,stage:"answer_generation",maxRequestRetries:3,onAttempt:(attempt)=>recordAttempt({attempt,stage:"answer_generation",qid:a.topic.qid,out:a.out,env:a.env,summary:a.summary})});
      const val:any=draft.value; const subRefs:string[]=Array.isArray(val.references)?val.references.map(String):[]; const arr:any[]=Array.isArray(val.answer)?val.answer:[]; let addedThisRound=0;
      for(const s of arr){ if(typeof s?.text!=="string"||!s.text.trim())continue; const idxs:number[]=Array.isArray(s.citations)?s.citations:[]; const docids=[...new Set(idxs.map(i=>subRefs[i]).filter((d):d is string=>typeof d==="string"&&docs.some(x=>x.docid===d)))]; if(docids.length===0)continue; out.push({text:stripInlineCitations(s.text),docids}); addedThisRound++; }
      if(addedThisRound===0)break; // model had nothing new to add for this aspect
    }catch{break;}
    if(out.length>=POLICY.aspect_target_sentences)break; // gathered enough for this aspect
  }
  return{sentences:out,docsUsed};
}
async function generatePerAspectAnswer(a:{topic:TopicIdentity;o:IterativeOptions;llm:LlmClient;out:string;env:NodeJS.ProcessEnv;summary:any},aspects:string[],shared:Map<string,ReadDoc>):Promise<{references:string[];answer:{text:string;citations:number[]}[];perAspect:any[];docText:Map<string,string>}>{
  const docidText=new Map<string,string>([...shared.values()].map(d=>[d.docid,d.text]));
  const sentences:{text:string;docids:string[]}[]=[]; const perAspect:any[]=[];
  for(const aspect of aspects){ const r=await answerOneAspect(a,aspect,docidText,shared); sentences.push(...r.sentences); perAspect.push({aspect,docs:r.docsUsed,sentences:r.sentences.length}); }
  // v4-style reflection: find aspects still missing/thin, run extra passes for them.
  if(POLICY.reflection&&sentences.length>0){ try{
    const answerText=sentences.map(s=>s.text).join(" ");
    const rr=await a.llm.generate({messages:[{role:"user",content:buildReflectionPrompt(a.topic,answerText)}],temperature:0,maxTokens:400,responseFormat:"json_object"});
    const j=extractObjectCandidate(rr.text); const gaps:string[]=j?((JSON.parse(j)?.gaps)||[]).map((x:any)=>String(x).trim()).filter((x:string)=>x.length>0).slice(0,POLICY.reflection_max_gaps):[];
    for(const gap of gaps){ const r=await answerOneAspect(a,gap,docidText,shared); sentences.push(...r.sentences); perAspect.push({aspect:`[reflect] ${gap}`,docs:r.docsUsed,sentences:r.sentences.length}); }
  }catch{} }
  // Cap to the official 1024-word limit (keep a margin): trim trailing sentences if over budget.
  const capped:{text:string;docids:string[]}[]=[]; let words=0;
  for(const s of sentences){ const w=s.text.split(/\s+/).filter(Boolean).length; if(words+w>1000&&capped.length>0)break; capped.push(s); words+=w; }
  const refs:string[]=[]; const idxOf=new Map<string,number>();
  for(const s of capped)for(const d of s.docids)if(!idxOf.has(d)){idxOf.set(d,refs.length);refs.push(d);}
  const answer=capped.map(s=>({text:s.text,citations:s.docids.map(d=>idxOf.get(d)!).slice(0,3)}));
  return{references:refs,answer,perAspect,docText:docidText};
}
// ④ LLM grounded revision: one LLM call reads each sentence + its cited docs, rewrites over-claims,
// weakens/drops unsupported claims, fixes citations. Stronger than BGE relevance for the support metric.
async function groundedReviseAnswer(a:{topic:TopicIdentity;llm:LlmClient},draft:{references:string[];answer:{text:string;citations:number[]}[]},docText:Map<string,string>):Promise<{references:string[];answer:{text:string;citations:number[]}[]}|null>{
  const refs=draft.references; if(refs.length===0||draft.answer.length===0)return null;
  const sents=draft.answer.map(s=>({text:s.text,docids:[...new Set(s.citations.map(c=>refs[c]).filter(Boolean))]}));
  const citedDocids=[...new Set(sents.flatMap(s=>s.docids))]; if(citedDocids.length===0)return null;
  const citedDocs=citedDocids.map(d=>({docid:d,text:(docText.get(d)??"").slice(0,POLICY.revise_snippet_chars)}));
  try{
    const r=await a.llm.generate({messages:[{role:"user",content:buildGroundedRevisionPrompt(a.topic,sents,citedDocs)}],temperature:0,maxTokens:POLICY.revise_max_tokens,responseFormat:"json_object"});
    const j=extractObjectCandidate(r.text); if(!j)return null; const arr:any[]=(JSON.parse(j)?.answer)||[];
    const out:{text:string;docids:string[]}[]=[];
    for(const s of arr){ if(typeof s?.text!=="string"||!s.text.trim())continue; const rc:any[]=Array.isArray(s.citations)?s.citations:[]; const dc:string[]=[...new Set(rc.map((c:any)=>String(c)).filter((d:string)=>docText.has(d)))].slice(0,3); if(dc.length===0)continue; out.push({text:s.text.trim(),docids:dc}); }
    if(out.length===0)return null;
    const newRefs:string[]=[]; const idx=new Map<string,number>();
    for(const s of out)for(const d of s.docids)if(!idx.has(d)){idx.set(d,newRefs.length);newRefs.push(d);}
    return{references:newRefs,answer:out.map(s=>({text:s.text,citations:s.docids.map(d=>idx.get(d)!)}))};
  }catch{return null;}
}
async function decomposeAspects(a:{topic:TopicIdentity;llm:LlmClient;out:string;env:NodeJS.ProcessEnv;summary:any}):Promise<string[]>{try{const r=await a.llm.generate({messages:[{role:"user",content:buildAspectDecompositionPrompt(a.topic)}],temperature:0,maxTokens:600,responseFormat:"json_object"}); const j=extractObjectCandidate(r.text); if(!j)return []; const parsed=JSON.parse(j); const arr=Array.isArray(parsed?.aspects)?parsed.aspects:[]; return arr.map((x:any)=>String(x).trim()).filter((x:string)=>x.length>0).slice(0,8);}catch{return [];}}
async function answer(a:{topic:TopicIdentity;o:IterativeOptions;cfg:AgenticRagBaselineConfig;llm:LlmClient;readDocs:Map<string,ReadDoc>;out:string;env:NodeJS.ProcessEnv;summary:any}){
if(a.env.R_ONLY==="1"){const s=sanitizeAnswerDraft(buildExtractiveFallbackAnswerDraft(a.readDocs)); const full:AgenticRagOutputObject={metadata:{team_id:a.cfg.teamId,run_id:a.cfg.runId,type:"automatic",narrative_id:a.topic.qid,title:"",narrative:a.topic.narrative,prompt:a.cfg.promptVersion,generator:a.llm.model,retrieval_depth:POLICY.output_depth},references:s.references,answer:s.answer}; return normalizeRagOutputObjectReferences(full,{config:a.cfg,topic:a.topic,readDocids:new Set(a.readDocs.keys())}).ragObject;}
let draft:any; const docs=[...a.readDocs.values()];
// v4-style comprehensive generation: decompose narrative into aspects, then require the answer to cover each. Feed ALL read docs (not just 6). Drives coverage.
const aspects=(POLICY.comprehensive_answer||POLICY.per_aspect_generation)?await decomposeAspects(a):[];
let perAspectTrace:any=null; const extraDocText=new Map<string,string>();
// v4-port: per-aspect generation first. If it yields a usable answer, use it; otherwise fall back to comprehensive single-call, then compact, then extractive.
if(POLICY.per_aspect_generation&&aspects.length>0){try{const pa=await generatePerAspectAnswer({topic:a.topic,o:a.o,llm:a.llm,out:a.out,env:a.env,summary:a.summary},aspects,a.readDocs); perAspectTrace=pa.perAspect; for(const [k,v] of pa.docText)extraDocText.set(k,v); if(pa.answer.length>=Math.min(3,aspects.length))draft={value:{references:pa.references,answer:pa.answer}};}catch{}}
if(!draft){try{const promptDocs=docs.map(d=>({docid:d.docid,text:d.text.slice(0,POLICY.answer_doc_chars)})); draft=await generateJsonWithRetry({client:a.llm,messages:[{role:"user",content:POLICY.comprehensive_answer?buildComprehensiveAnswerPrompt({topic:a.topic,documents:promptDocs,aspects}):buildAnswerGenerationPrompt({topic:a.topic,documents:docs.slice(0,6).map(d=>({docid:d.docid,text:d.text.slice(0,1000)}))})}],temperature:0,maxTokens:POLICY.answer_max_tokens,validate:validateAnswer,stage:"answer_generation",maxRequestRetries:4,onAttempt:(attempt)=>recordAttempt({attempt,stage:"answer_generation",qid:a.topic.qid,out:a.out,env:a.env,summary:a.summary})});}catch{try{draft=await generateJsonWithRetry({client:a.llm,messages:[{role:"user",content:buildCompactAnswerGenerationPrompt({topic:a.topic,documents:docs.slice(0,5).map(d=>({docid:d.docid,text:d.text.slice(0,800)}))})}],temperature:0,maxTokens:2000,validate:validateAnswer,stage:"answer_generation",maxRequestRetries:4,onAttempt:(attempt)=>recordAttempt({attempt,stage:"answer_generation",qid:a.topic.qid,out:a.out,env:a.env,summary:a.summary})});}catch{draft={value:buildExtractiveFallbackAnswerDraft(a.readDocs)}}}} let sanitized=sanitizeAnswerDraft(draft.value); if(sanitized.answer.length===0)sanitized=sanitizeAnswerDraft(buildExtractiveFallbackAnswerDraft(a.readDocs));
// Grounded citation verification: drop citations whose cited doc does not actually support the sentence. Logs before/after so support gain is attributable.
{const docText=new Map<string,string>([...a.readDocs.values()].map(d=>[d.docid,d.text])); for(const [k,v] of extraDocText)if(!docText.has(k))docText.set(k,v);
let verifyStats:any=null;
// Re-attribution (CiteFix/VeriCite style): re-point each sentence's citation to the best-supporting
// reference via BGE-Reranker. Preserves coverage (sentence stays) while fixing support. Falls back to
// the keyword-overlap verify if re-attribution fails/disabled.
if(POLICY.llm_revise){try{const rev=await groundedReviseAnswer({topic:a.topic,llm:a.llm},sanitized as any,docText); if(rev&&rev.answer.length>0){sanitized=rev as any; verifyStats={mode:"llm_revise",sentences:rev.answer.length};}}catch{}}
if(!verifyStats&&POLICY.reattribute){try{const r=await reattributeCitations(sanitized as any,docText,a.env,{threshold:POLICY.reattribute_threshold,maxCites:POLICY.reattribute_max_cites,snippetChars:1500}); if(r.draft.answer.length>0){sanitized=r.draft as any; verifyStats={mode:"reattribute",...r.stats};}}catch{}}
if(!verifyStats&&POLICY.citation_verify){const v=verifyCitations(sanitized as any,docText,{supportThreshold:POLICY.support_threshold}); if(v.draft.answer.length>0)sanitized=v.draft as any; else sanitized=sanitizeAnswerDraft(buildExtractiveFallbackAnswerDraft(a.readDocs)); verifyStats={mode:"keyword",...v.stats};}
writeJson(join(a.out,"topics",`${a.topic.qid}.gen_trace.json`),{topic_id:a.topic.qid,aspects,per_aspect:perAspectTrace,verify:verifyStats});}
const full:AgenticRagOutputObject={metadata:{team_id:a.cfg.teamId,run_id:a.cfg.runId,type:"automatic",narrative_id:a.topic.qid,title:"",narrative:a.topic.narrative,prompt:a.cfg.promptVersion,generator:a.llm.model,retrieval_depth:POLICY.output_depth},references:sanitized.references,answer:sanitized.answer}; return normalizeRagOutputObjectReferences(full,{config:a.cfg,topic:a.topic,readDocids:new Set(a.readDocs.keys())}).ragObject;}
// The LLM occasionally miscounts and cites a references[] index that doesn't exist
// (CITATION_OUT_OF_RANGE). Rather than failing the whole topic on a single formatting
// slip, drop the invalid citation indices and drop any sentence left with none.
function sanitizeAnswerDraft(draft:AnswerDraft):AnswerDraft{
  const refCount=Array.isArray(draft.references)?draft.references.length:0;
  const answer=(Array.isArray(draft.answer)?draft.answer:[])
    .map(sentence=>({
      text:typeof sentence?.text==="string"?sentence.text:"",
      citations:[...new Set((Array.isArray(sentence?.citations)?sentence.citations:[]).filter(c=>Number.isInteger(c)&&c>=0&&c<refCount))],
    }))
    .filter(sentence=>sentence.text.trim()!==""&&sentence.citations.length>0);
  return{references:Array.isArray(draft.references)?draft.references:[],answer};
}
function validateAnswer(v:unknown):LlmJsonValidationResult<AnswerDraft>{return isRecord(v)&&Array.isArray(v.references)&&Array.isArray(v.answer)?{ok:true,value:v as AnswerDraft}:{ok:false,message:"answer shape"};}
async function readNew(a:{o:IterativeOptions;hits:Hit[];readDocs:Map<string,ReadDoc>;failedRead:string[];count:number;query:string;env:NodeJS.ProcessEnv}){let added=0; for(const [i,h] of a.hits.entries()){if(added>=a.count||a.readDocs.size>=a.o.maxDocumentsRead)return; if(a.readDocs.has(h.docid))continue; try{const d=await readDoc(a.o,h.docid,a.o.documentReadLimit,a.env); if(d.found){a.readDocs.set(h.docid,{docid:h.docid,text:d.text,truncated:d.truncated,rankHint:i+1,query:a.query}); added++;}else a.failedRead.push(h.docid);}catch{a.failedRead.push(h.docid)} await sleep(200);}}
async function search(o:IterativeOptions,query:string,depth:number,env:NodeJS.ProcessEnv){const token=env[o.pyseriniTokenEnv]?.trim(); const url=`${o.pyseriniBaseUrl.replace(/\/+$/,'')}/v1/${o.pyseriniIndex}/search?${new URLSearchParams({query,hits:String(depth)})}`; for(let a=1;a<=8;a++){let r:Response; try{r=await fetch(url,{headers:token?{authorization:`Bearer ${token}`}:{}});}catch(e){if(a===8)throw new Error(`Pyserini fetch failed: ${e instanceof Error?e.message:String(e)}`); await sleep(Math.max(1000,600*2**a)); continue;} if(r.ok){const v=await r.json() as any; return (v.candidates??[]).filter((c:any)=>typeof c.docid==='string').map((c:any)=>({docid:c.docid,score:Number(c.score)||0})).slice(0,depth)} if(![429,500,502,503,504].includes(r.status)||a===8)throw new Error(`Pyserini HTTP ${r.status}`); await sleep(Math.max(1000,600*2**a));} throw new Error('search failed')}
async function readDoc(o:IterativeOptions,docid:string,limit:number,env:NodeJS.ProcessEnv){const token=env[o.pyseriniTokenEnv]?.trim(); const url=`${o.pyseriniBaseUrl.replace(/\/+$/,'')}/v1/${o.pyseriniIndex}/doc/${encodeURIComponent(docid)}`; const maxAttempts=10; for(let a=1;a<=maxAttempts;a++){let r:Response; try{r=await fetch(url,{headers:token?{authorization:`Bearer ${token}`}:{}});}catch(e){if(a===maxAttempts)throw new Error(`Pyserini doc fetch failed: ${e instanceof Error?e.message:String(e)}`); await sleep(Math.max(1000,600*2**a)); continue;} if(r.status===404)return{found:false,text:"",truncated:false}; if(r.ok){const v=await r.json() as any; const text=extractText(v.doc), lines=text.split(/\r?\n/); return{found:true,text:lines.slice(0,limit).join('\n'),truncated:lines.length>limit}} if(![429,500,502,503,504].includes(r.status)||a===maxAttempts)throw new Error(`Pyserini doc HTTP ${r.status}`); await sleep(r.status===429?Math.min(30000,2000*2**a):Math.max(1000,600*2**a));} throw new Error('read failed')}
function weightedRrf(rs:Hit[][],ws:number[],depth:number,k:number){const m=new Map<string,{score:number;best:number}>();rs.forEach((hits,ri)=>hits.forEach((h,i)=>{const p=m.get(h.docid)??{score:0,best:Infinity};p.score+=(ws[ri]??1)/(k+i+1);p.best=Math.min(p.best,i+1);m.set(h.docid,p)}));return[...m.entries()].sort((a,b)=>b[1].score-a[1].score||a[1].best-b[1].best||a[0].localeCompare(b[0])).slice(0,depth).map(([docid,v],i)=>({docid,rank:i+1,score:v.score}))}
function buildRetrievalTrace(topic:TopicIdentity,queries:string[],runs:Hit[][],ranking:ReturnType<typeof weightedRrf>){return{topic_id:topic.qid,policy:POLICY,anchor_query:topic.narrative,followup_queries:queries.slice(1),query_count:queries.length,per_query_top10:runs.map((h,i)=>({query:queries[i],weight:i===0?POLICY.bm25_anchor_weight:(typeof queries[i]==="string"&&queries[i].startsWith("[query2doc]"))?POLICY.q2d_weight:POLICY.followup_query_weight,top10:h.slice(0,10)})),fused_top10:ranking.slice(0,10),candidate_count:ranking.length}}
function writeTopicPartial(a:{out:string;topic:TopicIdentity;iterationTrace:any[];judgeTrace:any[];queries:string[];runs:Hit[][];ranking:ReturnType<typeof weightedRrf>;readDocs:Map<string,ReadDoc>;failedRead:string[]}){const base=join(a.out,"topics"); writeJson(join(base,`${a.topic.qid}.iteration_trace.json`),a.iterationTrace); writeJson(join(base,`${a.topic.qid}.judge_trace.json`),a.judgeTrace); writeJson(join(base,`${a.topic.qid}.retrieval-trace.json`),buildRetrievalTrace(a.topic,a.queries,a.runs,a.ranking)); writeJson(join(base,`${a.topic.qid}.final_read_docs_trace.json`),{topic_id:a.topic.qid,candidate_pool_size:a.ranking.length,documents_read_attempted:a.readDocs.size+a.failedRead.length,documents_read_successful:a.readDocs.size,read_docids:[...a.readDocs.keys()],failed_read_docids:a.failedRead,final_answer_cited_docids:[]});}
function classifyJudgeStopReason(message:string){if(/empty assistant message/i.test(message))return"judge_empty_assistant_message"; if(/429|rate limit/i.test(message))return"judge_rate_limit"; if(/5\\d\\d|server/i.test(message))return"judge_server_error"; if(/fetch failed|network|timeout|timed out|ECONNRESET|ETIMEDOUT/i.test(message))return"judge_transient_request_failed"; return"judge_json_parse_failed";}
function recordAttempt(a:{attempt:LlmAttemptTrace;stage:string;qid:string;out:string;env:NodeJS.ProcessEnv;summary:any}){a.summary.llm_call_count++; if(!a.attempt.success)a.summary.llm_failed_call_count++; if(a.attempt.attempt>1)a.summary.llm_retry_count++; appendJsonl(join(a.out,"llm_trace.jsonl"),{qid:a.qid,stage:a.stage,attempt:a.attempt.attempt,success:a.attempt.success,error_code:a.attempt.errorCode,provider:a.attempt.provider,model:a.attempt.model,latency_ms:a.attempt.latencyMs,output_chars:a.attempt.outputChars},a.env)}
function extractText(doc:any){return typeof doc==='string'?doc:(doc&&typeof doc.text==='string'?doc.text:JSON.stringify(doc??''))} function topicRun(qid:string,r:any[],runId:string){return r.map((e,i)=>`${qid} Q0 ${e.docid} ${i+1} ${e.score.toFixed(8)} ${runId}`).join('\n')+'\n'} function render(r:Rankings,qids:string[],runId:string){return qids.flatMap(q=>(r.get(q)??[]).map((e,i)=>`${q} Q0 ${e.docid} ${i+1} ${e.score.toFixed(8)} ${runId}`)).join('\n')+'\n'} function assemble(out:string,topics:Topic[]):Rankings{const r:Rankings=new Map(); for(const t of topics){const p=join(out,"topics",`${t.qid}.runfile.trec`); if(existsSync(p))r.set(t.qid,readFileSync(p,'utf8').split(/\r?\n/).filter(Boolean).map(line=>{const[,,docid,rank,score]=line.split(/\s+/);return{docid,rank:Number(rank),score:Number(score)}}))} return r}
function qrelsPaths(dir:string){return['rag25-climbmix-umbrela-codex-gpt5.5-medium-reasoning-v1.qrels','rag25-climbmix-umbrela-ministral-3-14b-instruct-2512-v2.qrels','rag25-climbmix-umbrela-qwen3.5-9b-v2.qrels'].map(n=>join(dir,n))} function parseQrels(path:string,qids:string[]):Qrels{const w=new Set(qids),q:Qrels=new Map(); for(const line of readFileSync(path,'utf8').split(/\r?\n/)){if(!line.trim())continue; const[qid,,docid,rel]=line.split(/\s+/); if(!w.has(qid))continue; const m=q.get(qid)??new Map<string,number>(); m.set(docid,Number(rel)||0); q.set(qid,m)} return q} function evalAll(paths:string[],qids:string[],rankings:Rankings){const rows=paths.map(p=>{const q=parseQrels(p,qids),res=evaluateRankings(q,rankings,qids,{recallCutoffs:CUTS,ndcgCutoffs:NDCG,mrrCutoffs:[1000]},{recallRelevantThreshold:2,binaryRelevantThreshold:2,ndcgGainMode:'linear'}); const metrics={ndcg_10:res.ndcgByCutoff.get(10)??0,ndcg_20:res.ndcgByCutoff.get(20)??0,ndcg_100:res.ndcgByCutoff.get(100)??0,ndcg_1000:res.ndcgByCutoff.get(1000)??0,recall_20:res.macroRecallByCutoff.get(20)??0,recall_100:res.macroRecallByCutoff.get(100)??0,recall_500:res.macroRecallByCutoff.get(500)??0,recall_1000:res.macroRecallByCutoff.get(1000)??0,map:res.map,mrr:res.mrrByCutoff.get(1000)??0}; return{qrels_path:p,qrels_filename:basename(p),metrics,per_topic:{}}}); const keys=Object.keys(rows[0].metrics); return{summary:{qrels:rows.map(({per_topic:_p,...x})=>x),arithmetic_mean_across_qrels:Object.fromEntries(keys.map(k=>[k,rows.reduce((s:any,r:any)=>s+(r.metrics as any)[k],0)/rows.length]))},perTopic:{}}}
function writeJson(p:string,v:any){mkdirSync(dirname(p),{recursive:true});writeFileSync(p,JSON.stringify(v,null,2)+'\n')} function writeJsonl(p:string,rows:any[]){writeFileSync(p,rows.map(r=>JSON.stringify(r)).join('\n')+(rows.length?'\n':''))} function appendJsonl(p:string,v:any,_env:NodeJS.ProcessEnv){mkdirSync(dirname(p),{recursive:true});writeFileSync(p,JSON.stringify(v)+'\n',{flag:'a'})} function readIf(p:string):any{return existsSync(p)?JSON.parse(readFileSync(p,'utf8')):null} function isRecord(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v)} function sleep(ms:number){return new Promise(r=>setTimeout(r,ms))} function redact(s:string,env:NodeJS.ProcessEnv){for(const k of ['NCHC_API_KEY','PYSERINI_API_TOKEN']){const v=env[k]; if(v)s=s.split(v).join(`[redacted ${k}]`)} return s}
